apiVersion: apps/v1
kind: Deployment
metadata:
  name: quine-client-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quine-client
  template:
    metadata:
      labels:
        app: quine-client
    spec:
      containers:
        - name: redis-cli
          image: redis:alpine
          command: ["/bin/sh", "-c"]
          args: ["while true; do sleep 3600; done"]
