apiVersion: v1
kind: Service
metadata:
  name: quine-db-headless
  labels:
    app: quine-db
spec:
  ports:
    - port: 6379
      name: resp
  clusterIP: None
  selector:
    app: quine-db
---
apiVersion: v1
kind: Service
metadata:
  name: quine-db-service
  labels:
    app: quine-db
spec:
  type: ClusterIP # Or LoadBalancer for external access
  ports:
    - port: 6379
      targetPort: 6379
      name: resp
  selector:
    app: quine-db
